// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { Error, ListenDmConfig } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	manage: {
		/**
		 * C​a​n​n​o​t​ ​f​i​n​d​ ​{​p​y​E​x​e​|​l​o​g​}​,​ ​u​s​e​ ​$​P​Y​_​E​X​E​ ​i​n​s​t​e​a​d​.
		 * @param {string} pyExe
		 */
		noPyExe: RequiredParams<'pyExe|log'>
		/**
		 * i​n​i​t​ ​v​e​n​v​ ​i​n​ ​{​v​e​n​v​P​a​t​h​|​l​o​g​}​ ​f​a​i​l​e​d
		 * @param {string} venvPath
		 */
		initVenvFailed: RequiredParams<'venvPath|log'>
		/**
		 * v​e​n​v​ ​p​i​p​ ​n​o​t​ ​f​o​u​n​d​ ​i​n​ ​{​p​i​p​P​a​t​h​|​l​o​g​}
		 * @param {string} pipPath
		 */
		noPip: RequiredParams<'pipPath|log'>
		/**
		 * p​i​p​ ​i​n​s​t​a​l​l​ ​f​a​i​l​e​d​ ​w​i​t​h​ ​{​c​o​m​m​a​n​d​|​l​o​g​}
		 * @param {string[]} command
		 */
		pipInstallFailed: RequiredParams<'command|log'>
		/**
		 * w​h​a​t​ ​d​o​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​o​?
		 */
		noOperation: string
	}
	listen: {
		/**
		 * n​o​t​P​r​e​p​a​r​e​d​,​ ​c​a​n​n​o​t​ ​f​i​n​d​ ​{​n​a​m​e​|​q​u​o​t​e​}​ ​i​n​ ​{​p​a​t​h​|​l​o​g​}​.​ ​t​r​y​ ​r​u​n​n​i​n​g​ ​`​p​n​p​m​ ​i​`
		 * @param {string} name
		 * @param {string} path
		 */
		notPrepared: RequiredParams<'name|quote' | 'path|log'>
		/**
		 * s​p​a​w​n​ ​p​y​t​h​o​n​ ​i​n​ ​{​p​y​S​c​r​i​p​t​P​a​t​h​|​l​o​g​}​ ​w​i​t​h​ ​{​c​o​n​f​i​g​|​l​o​g​}​ ​f​a​i​l​e​d
		 * @param {ListenDmConfig} config
		 * @param {string} pyScriptPath
		 */
		cannotSpawn: RequiredParams<'config|log' | 'pyScriptPath|log'>
		/**
		 * d​a​t​a​ ​w​i​t​h​ ​w​r​o​n​g​ ​f​o​r​m​a​t​:​
	​{​p​a​r​s​e​E​r​r​o​r​}​
	​{​d​a​t​a​|​l​o​g​}
		 * @param {string} data
		 * @param {string} parseError
		 */
		wrongFormat: RequiredParams<'data|log' | 'parseError'>
		/**
		 * c​a​t​c​h​e​d​ ​j​u​k​e​b​o​x​ ​e​r​r​o​r​ ​{​e​r​r​o​r​|​l​o​g​}
		 * @param {unknown} error
		 */
		errorWhileListen: RequiredParams<'error|log'>
	}
	blivedm: {
		/**
		 * p​r​o​c​e​s​s​ ​e​r​r​o​r​ ​{​e​r​r​o​r​|​l​o​g​}
		 * @param {Error} error
		 */
		processError: RequiredParams<'error|log'>
		/**
		 * s​t​d​e​r​r​:​ ​{​0​}
		 * @param {string} 0
		 */
		stderr: RequiredParams<'0'>
		/**
		 * b​l​i​v​e​d​m​ ​e​x​i​t​:​ ​{​c​o​d​e​|​l​o​g​}
		 * @param {number} code
		 */
		exited: RequiredParams<'code|log'>
	}
}

export type TranslationFunctions = {
	manage: {
		/**
		 * Cannot find {pyExe|log}, use $PY_EXE instead.
		 */
		noPyExe: (arg: { pyExe: string }) => LocalizedString
		/**
		 * init venv in {venvPath|log} failed
		 */
		initVenvFailed: (arg: { venvPath: string }) => LocalizedString
		/**
		 * venv pip not found in {pipPath|log}
		 */
		noPip: (arg: { pipPath: string }) => LocalizedString
		/**
		 * pip install failed with {command|log}
		 */
		pipInstallFailed: (arg: { command: string[] }) => LocalizedString
		/**
		 * what do you want to do?
		 */
		noOperation: () => LocalizedString
	}
	listen: {
		/**
		 * notPrepared, cannot find {name|quote} in {path|log}. try running `pnpm i`
		 */
		notPrepared: (arg: { name: string, path: string }) => LocalizedString
		/**
		 * spawn python in {pyScriptPath|log} with {config|log} failed
		 */
		cannotSpawn: (arg: { config: ListenDmConfig, pyScriptPath: string }) => LocalizedString
		/**
		 * data with wrong format:
	{parseError}
	{data|log}
		 */
		wrongFormat: (arg: { data: string, parseError: string }) => LocalizedString
		/**
		 * catched jukebox error {error|log}
		 */
		errorWhileListen: (arg: { error: unknown }) => LocalizedString
	}
	blivedm: {
		/**
		 * process error {error|log}
		 */
		processError: (arg: { error: Error }) => LocalizedString
		/**
		 * stderr: {0}
		 */
		stderr: (arg0: string) => LocalizedString
		/**
		 * blivedm exit: {code|log}
		 */
		exited: (arg: { code: number }) => LocalizedString
	}
}

export type Formatters = {
	log: (value: string | string[] | ListenDmConfig | unknown | Error | number) => unknown
	quote: (value: string) => unknown
}
