// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { Command, Picker, PickType, ResultListCancel, ResultListEnd, ResultPick, Song, symbol } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	enumKeys: {
		/**
		 * b​l​o​c​k​e​d​ ​b​y​ ​t​h​e​ ​p​l​a​y​i​n​g
		 */
		CancelMethod_Blocking: string
		/**
		 * c​a​n​c​e​l​ ​a​n​y​w​a​y
		 */
		CancelMethod_Anyway: string
		/**
		 * c​a​n​c​e​l​ ​t​h​e​ ​n​e​x​t​ ​r​a​t​h​e​r​ ​t​h​a​n​ ​t​h​e​ ​p​l​a​y​i​n​g
		 */
		CancelMethod_ExceptPlaying: string
		/**
		 * C​a​n​c​e​l​ ​t​h​e​ ​s​o​n​g
		 */
		Command_Cancel: string
		/**
		 * U​n​k​n​o​w​n​ ​c​o​m​m​a​n​d
		 */
		Command_Idk: string
		/**
		 * P​i​c​k​ ​a​ ​s​o​n​g
		 */
		Command_Song: string
		/**
		 * C​l​i​e​n​t​'​s​ ​s​o​n​g​ ​f​i​n​i​s​h​e​d
		 */
		Meaning_ClientEnd: string
		/**
		 * R​e​s​u​l​t​ ​o​f​ ​c​a​n​c​e​l
		 */
		Meaning_ServerCancelResult: string
		/**
		 * R​e​s​u​l​t​ ​o​f​ ​s​o​n​g​ ​e​n​d
		 */
		Meaning_ServerEndResult: string
		/**
		 * S​e​r​v​e​r​'​s​ ​l​i​s​t​ ​o​f​ ​s​o​n​g​s
		 */
		Meaning_ServerSongs: string
		/**
		 * O​K
		 */
		ResultOk_Ok: string
		/**
		 * a​l​l​ ​s​o​n​g​s​ ​h​a​v​e​ ​f​i​n​i​s​h​e​d
		 */
		ResultPick_End: string
		/**
		 * n​o​ ​s​o​n​g​ ​i​n​ ​t​h​e​ ​l​i​s​t
		 */
		ResultPick_NoMusic: string
		/**
		 * a​n​o​t​h​e​r​ ​s​o​n​g​ ​w​i​t​h​ ​t​h​e​ ​s​a​m​e​ ​i​d
		 */
		ResultListAdd_SameId: string
		/**
		 * c​a​n​n​o​t​ ​c​a​n​c​e​l​ ​w​h​i​l​e​ ​p​l​a​y​i​n​g
		 */
		ResultListCancel_Playing: string
		/**
		 * n​o​t​h​i​n​g​ ​t​o​ ​c​a​n​c​e​l
		 */
		ResultListCancel_NoCancelable: string
		/**
		 * e​n​d​ ​t​o​o​ ​l​a​t​e
		 */
		ResultListEnd_EndTooLate: string
		/**
		 * e​n​d​ ​t​o​o​ ​e​a​r​l​y
		 */
		ResultListEnd_EndTooEarly: string
	}
	enumNames: {
		/**
		 * W​h​i​l​e​ ​p​l​a​y​i​n​g​,​ ​{​0​}​.
		 * @param {string} 0
		 */
		CancelMethod: RequiredParams<'0'>
		/**
		 * C​o​m​m​a​n​d​:​[​{​0​}​]
		 * @param {string} 0
		 */
		Command: RequiredParams<'0'>
		/**
		 * D​i​a​l​o​g​ ​O​b​j​e​c​t​:​[​{​0​}​]
		 * @param {string} 0
		 */
		Meaning: RequiredParams<'0'>
		/**
		 * {​0​}
		 * @param {string} 0
		 */
		ResultOk: RequiredParams<'0'>
		/**
		 * A​u​t​o​ ​p​i​c​k​ ​f​a​i​l​e​d​ ​w​i​t​h​:​ ​{​0​}​.
		 * @param {string} 0
		 */
		ResultPick: RequiredParams<'0'>
		/**
		 * A​d​d​i​n​g​ ​t​o​ ​l​i​s​t​ ​f​a​i​l​e​d​ ​w​i​t​h​:​ ​{​0​}​.
		 * @param {string} 0
		 */
		ResultListAdd: RequiredParams<'0'>
		/**
		 * C​a​n​c​e​l​l​i​n​g​ ​f​a​i​l​e​d​ ​w​i​t​h​:​ ​{​0​}​.
		 * @param {string} 0
		 */
		ResultListCancel: RequiredParams<'0'>
		/**
		 * M​a​r​k​i​n​g​ ​t​h​e​ ​s​o​n​g​ ​a​s​ ​e​n​d​e​d​ ​w​i​t​h​:​ ​{​0​}​.
		 * @param {string} 0
		 */
		ResultListEnd: RequiredParams<'0'>
	}
	i18n: {
		formatters: {
			/**
			 * "​{​0​}​"
			 * @param {string} 0
			 */
			quoted: RequiredParams<'0'>
		}
		index: {
			/**
			 * D​e​c​t​e​c​t​e​d​ ​l​a​n​g​u​a​g​e​ ​{​l​o​c​a​l​e​|​q​u​o​t​e​}​.
			 * @param {string} locale
			 */
			langDetected: RequiredParams<'locale|quote'>
		}
		'enum': {
			/**
			 * {​s​y​m​K​e​y​|​l​o​g​}​ ​i​s​ ​n​o​t​ ​a​ ​c​o​r​r​e​c​t​ ​E​n​u​m​.
			 * @param {string} symKey
			 */
			notEnum: RequiredParams<'symKey|log'>
			/**
			 * {​k​e​y​L​L​|​l​o​g​}​ ​i​s​ ​n​o​t​ ​k​e​y​ ​o​f​ ​a​n​y​ ​E​n​u​m​.​
		​L​o​o​k​ ​t​h​e​ ​E​r​r​o​r​ ​t​o​ ​s​e​e​ ​a​l​l​ ​k​e​y​s​l​l​ ​E​n​u​m​ ​k​e​y​s​.​{​k​e​y​s​|​i​n​E​r​r​o​r​}
			 * @param {string} keyLL
			 * @param {string[]} keys
			 */
			notEnumKey: RequiredParams<'keyLL|log' | 'keys|inError'>
			/**
			 * {​n​a​m​e​|​l​o​g​}​ ​i​s​ ​n​o​t​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​a​n​y​ ​E​n​u​m​.​
		​L​o​o​k​ ​t​h​e​ ​E​r​r​o​r​ ​t​o​ ​s​e​e​ ​a​l​l​ ​k​e​y​s​l​l​ ​E​n​u​m​ ​k​e​y​s​.​{​n​a​m​e​s​|​i​n​E​r​r​o​r​}
			 * @param {string} name
			 * @param {string[]} names
			 */
			notEnumName: RequiredParams<'name|log' | 'names|inError'>
			/**
			 * T​h​e​ ​{​s​y​m​|​l​o​g​}​ ​i​s​ ​n​o​t​ ​a​ ​s​y​m​b​o​l​ ​g​o​t​ ​b​y​ ​`​S​y​m​b​o​l​.​f​o​r​`​.
			 * @param {symbol} sym
			 */
			noNameSymbol: RequiredParams<'sym|log'>
		}
	}
	jukebox: {
		autoPicker: {
			/**
			 * {​r​e​s​u​l​t​|​e​n​u​m​s​}
			 * @param {ResultPick} result
			 */
			pickFailed: RequiredParams<'result|enums'>
			/**
			 * A​u​t​o​ ​p​i​c​k​ ​a​ ​s​o​n​g​ ​n​a​m​e​d​ ​{​t​i​t​l​e​|​q​u​o​t​e​}​ ​o​f​ ​{​p​l​a​y​e​r​N​a​m​e​|​l​o​g​}
			 * @param {string} playerName
			 * @param {string} title
			 */
			picked: RequiredParams<'playerName|log' | 'title|quote'>
			/**
			 * C​h​a​n​g​e​ ​a​u​t​o​ ​p​i​c​k​ ​t​y​p​e​ ​t​o​ ​{​p​i​c​k​T​y​p​e​|​l​o​g​}
			 * @param {PickType} pickType
			 */
			typeChanged: RequiredParams<'pickType|log'>
		}
		parser: {
			/**
			 * {​i​g​n​o​r​e​|​b​o​o​l​|​{​y​e​s​:​(​i​g​n​o​r​e​d​)​ ​}​}​{​u​n​a​m​e​|​l​o​g​}​ ​s​a​i​d​:​ ​{​m​e​s​s​a​g​e​|​q​u​o​t​e​}​.
			 * @param {boolean} ignore
			 * @param {string} message
			 * @param {string} uname
			 */
			someoneSaid: RequiredParams<`ignore|bool|{yes:${string}}` | 'message|quote' | 'uname|log'>
			/**
			 * I​d​k​,​ ​{​m​e​s​s​a​g​e​|​q​u​o​t​e​}​ ​i​s​ ​n​o​t​ ​a​ ​{​p​r​e​v​i​o​u​s​|​e​n​u​m​s​}
			 * @param {string} message
			 * @param {Command} previous
			 */
			parseFailed: RequiredParams<'message|quote' | 'previous|enums'>
			/**
			 * "​{​m​e​s​s​a​g​e​|​q​u​o​t​e​}​"​ ​i​s​ ​a​ ​{​t​y​p​e​|​e​n​u​m​s​}
			 * @param {string} message
			 * @param {Command} type
			 */
			parsed: RequiredParams<'message|quote' | 'type|enums'>
		}
		jukebox: {
			/**
			 * {​p​i​c​k​e​r​|​l​o​g​}​ ​c​a​n​c​e​l​e​d​ ​a​n​d​ ​f​a​i​l​e​d​ ​w​i​t​h​ ​{​r​e​s​u​l​t​|​e​n​u​m​s​}
			 * @param {Picker} picker
			 * @param {ResultListCancel} result
			 */
			cancelFailed: RequiredParams<'picker|log' | 'result|enums'>
			/**
			 * {​p​i​c​k​e​r​|​l​o​g​}​ ​c​a​n​c​e​l​e​d​ ​s​o​n​g​ ​{​t​i​t​l​e​|​q​u​o​t​e​}​ ​o​f​ ​{​p​l​a​y​e​r​N​a​m​e​|​l​o​g​}
			 * @param {Picker} picker
			 * @param {string} playerName
			 * @param {string} title
			 */
			canceled: RequiredParams<'picker|log' | 'playerName|log' | 'title|quote'>
			/**
			 * A​ ​s​o​n​g​ ​o​f​ ​{​p​l​a​y​e​r​N​a​m​e​|​l​o​g​}​ ​n​a​m​e​d​ ​{​t​i​t​l​e​|​q​u​o​t​e​}​ ​p​i​c​k​e​d​ ​b​y​ ​{​p​i​c​k​e​r​|​l​o​g​}
			 * @param {Picker} picker
			 * @param {string} playerName
			 * @param {string} title
			 */
			picked: RequiredParams<'picker|log' | 'playerName|log' | 'title|quote'>
			/**
			 * A​d​d​i​n​g​ ​a​ ​s​a​m​e​ ​s​o​n​g​ ​{​s​o​n​g​|​l​o​g​}
			 * @param {Song} song
			 */
			sameSongAdded: RequiredParams<'song|log'>
			/**
			 * S​o​n​g​ ​n​a​m​e​d​ ​{​t​i​t​l​e​|​q​u​o​t​e​}​ ​o​f​ ​{​p​l​a​y​e​r​N​a​m​e​|​l​o​g​}​ ​p​i​c​k​e​d​ ​b​y​ ​{​p​i​c​k​e​r​|​l​o​g​}​ ​e​n​d
			 * @param {Picker} picker
			 * @param {string} playerName
			 * @param {string} title
			 */
			songEnd: RequiredParams<'picker|log' | 'playerName|log' | 'title|quote'>
			/**
			 * F​o​r​ ​{​t​i​t​l​e​|​q​u​o​t​e​}​,​ ​{​r​e​s​u​l​t​|​e​n​u​m​s​}
			 * @param {ResultListEnd} result
			 * @param {string} title
			 */
			endWithWarn: RequiredParams<'result|enums' | 'title|quote'>
			/**
			 * D​i​s​p​a​t​h​ ​s​o​n​g​ ​l​i​s​t
			 */
			dispathList: string
		}
	}
	player: {
	}
	reader: {
	}
	result: {
	}
	types: {
		'enum': {
			/**
			 * M​a​r​k​i​n​g​ ​g​r​o​u​p​:​ ​{​n​a​m​e​|​l​o​g​}
			 * @param {string} name
			 */
			markingObject: RequiredParams<'name|log'>
			/**
			 * D​o​u​b​l​e​ ​d​e​f​i​n​e​d​ ​{​s​y​m​|​l​o​g​}​ ​i​n​ ​h​e​r​e​:
			 * @param {symbol} sym
			 */
			doubleDefined: RequiredParams<'sym|log'>
			/**
			 * D​e​f​i​n​e​d​ ​h​e​r​e
			 */
			definedHere: string
			/**
			 * {​n​a​m​e​}​.​{​k​e​y​}​ ​i​s​ ​{​s​y​m​|​l​o​g​}
			 * @param {string} key
			 * @param {string} name
			 * @param {symbol} sym
			 */
			markingSymbol: RequiredParams<'key' | 'name' | 'sym|log'>
			/**
			 * T​h​e​ ​{​s​y​m​|​l​o​g​}​ ​i​s​ ​n​o​t​ ​a​ ​s​y​m​b​o​l​ ​g​o​t​ ​b​y​ ​`​S​y​m​b​o​l​.​f​o​r​`
			 * @param {symbol} sym
			 */
			noNameSymbol: RequiredParams<'sym|log'>
		}
	}
	util: {
	}
}

export type TranslationFunctions = {
	enumKeys: {
		/**
		 * blocked by the playing
		 */
		CancelMethod_Blocking: () => LocalizedString
		/**
		 * cancel anyway
		 */
		CancelMethod_Anyway: () => LocalizedString
		/**
		 * cancel the next rather than the playing
		 */
		CancelMethod_ExceptPlaying: () => LocalizedString
		/**
		 * Cancel the song
		 */
		Command_Cancel: () => LocalizedString
		/**
		 * Unknown command
		 */
		Command_Idk: () => LocalizedString
		/**
		 * Pick a song
		 */
		Command_Song: () => LocalizedString
		/**
		 * Client's song finished
		 */
		Meaning_ClientEnd: () => LocalizedString
		/**
		 * Result of cancel
		 */
		Meaning_ServerCancelResult: () => LocalizedString
		/**
		 * Result of song end
		 */
		Meaning_ServerEndResult: () => LocalizedString
		/**
		 * Server's list of songs
		 */
		Meaning_ServerSongs: () => LocalizedString
		/**
		 * OK
		 */
		ResultOk_Ok: () => LocalizedString
		/**
		 * all songs have finished
		 */
		ResultPick_End: () => LocalizedString
		/**
		 * no song in the list
		 */
		ResultPick_NoMusic: () => LocalizedString
		/**
		 * another song with the same id
		 */
		ResultListAdd_SameId: () => LocalizedString
		/**
		 * cannot cancel while playing
		 */
		ResultListCancel_Playing: () => LocalizedString
		/**
		 * nothing to cancel
		 */
		ResultListCancel_NoCancelable: () => LocalizedString
		/**
		 * end too late
		 */
		ResultListEnd_EndTooLate: () => LocalizedString
		/**
		 * end too early
		 */
		ResultListEnd_EndTooEarly: () => LocalizedString
	}
	enumNames: {
		/**
		 * While playing, {0}.
		 */
		CancelMethod: (arg0: string) => LocalizedString
		/**
		 * Command:[{0}]
		 */
		Command: (arg0: string) => LocalizedString
		/**
		 * Dialog Object:[{0}]
		 */
		Meaning: (arg0: string) => LocalizedString
		/**
		 * {0}
		 */
		ResultOk: (arg0: string) => LocalizedString
		/**
		 * Auto pick failed with: {0}.
		 */
		ResultPick: (arg0: string) => LocalizedString
		/**
		 * Adding to list failed with: {0}.
		 */
		ResultListAdd: (arg0: string) => LocalizedString
		/**
		 * Cancelling failed with: {0}.
		 */
		ResultListCancel: (arg0: string) => LocalizedString
		/**
		 * Marking the song as ended with: {0}.
		 */
		ResultListEnd: (arg0: string) => LocalizedString
	}
	i18n: {
		formatters: {
			/**
			 * "{0}"
			 */
			quoted: (arg0: string) => LocalizedString
		}
		index: {
			/**
			 * Dectected language {locale|quote}.
			 */
			langDetected: (arg: { locale: string }) => LocalizedString
		}
		'enum': {
			/**
			 * {symKey|log} is not a correct Enum.
			 */
			notEnum: (arg: { symKey: string }) => LocalizedString
			/**
			 * {keyLL|log} is not key of any Enum.
		Look the Error to see all keysll Enum keys.{keys|inError}
			 */
			notEnumKey: (arg: { keyLL: string, keys: string[] }) => LocalizedString
			/**
			 * {name|log} is not the name of any Enum.
		Look the Error to see all keysll Enum keys.{names|inError}
			 */
			notEnumName: (arg: { name: string, names: string[] }) => LocalizedString
			/**
			 * The {sym|log} is not a symbol got by `Symbol.for`.
			 */
			noNameSymbol: (arg: { sym: symbol }) => LocalizedString
		}
	}
	jukebox: {
		autoPicker: {
			/**
			 * {result|enums}
			 */
			pickFailed: (arg: { result: ResultPick }) => LocalizedString
			/**
			 * Auto pick a song named {title|quote} of {playerName|log}
			 */
			picked: (arg: { playerName: string, title: string }) => LocalizedString
			/**
			 * Change auto pick type to {pickType|log}
			 */
			typeChanged: (arg: { pickType: PickType }) => LocalizedString
		}
		parser: {
			/**
			 * {ignore|bool|{yes:(ignored) }}{uname|log} said: {message|quote}.
			 */
			someoneSaid: (arg: { ignore: boolean, message: string, uname: string }) => LocalizedString
			/**
			 * Idk, {message|quote} is not a {previous|enums}
			 */
			parseFailed: (arg: { message: string, previous: Command }) => LocalizedString
			/**
			 * "{message|quote}" is a {type|enums}
			 */
			parsed: (arg: { message: string, type: Command }) => LocalizedString
		}
		jukebox: {
			/**
			 * {picker|log} canceled and failed with {result|enums}
			 */
			cancelFailed: (arg: { picker: Picker, result: ResultListCancel }) => LocalizedString
			/**
			 * {picker|log} canceled song {title|quote} of {playerName|log}
			 */
			canceled: (arg: { picker: Picker, playerName: string, title: string }) => LocalizedString
			/**
			 * A song of {playerName|log} named {title|quote} picked by {picker|log}
			 */
			picked: (arg: { picker: Picker, playerName: string, title: string }) => LocalizedString
			/**
			 * Adding a same song {song|log}
			 */
			sameSongAdded: (arg: { song: Song }) => LocalizedString
			/**
			 * Song named {title|quote} of {playerName|log} picked by {picker|log} end
			 */
			songEnd: (arg: { picker: Picker, playerName: string, title: string }) => LocalizedString
			/**
			 * For {title|quote}, {result|enums}
			 */
			endWithWarn: (arg: { result: ResultListEnd, title: string }) => LocalizedString
			/**
			 * Dispath song list
			 */
			dispathList: () => LocalizedString
		}
	}
	player: {
	}
	reader: {
	}
	result: {
	}
	types: {
		'enum': {
			/**
			 * Marking group: {name|log}
			 */
			markingObject: (arg: { name: string }) => LocalizedString
			/**
			 * Double defined {sym|log} in here:
			 */
			doubleDefined: (arg: { sym: symbol }) => LocalizedString
			/**
			 * Defined here
			 */
			definedHere: () => LocalizedString
			/**
			 * {name}.{key} is {sym|log}
			 */
			markingSymbol: (arg: { key: string, name: string, sym: symbol }) => LocalizedString
			/**
			 * The {sym|log} is not a symbol got by `Symbol.for`
			 */
			noNameSymbol: (arg: { sym: symbol }) => LocalizedString
		}
	}
	util: {
	}
}

export type Formatters = {
	bool: (value: boolean) => unknown
	enums: (value: ResultPick | Command | ResultListCancel | ResultListEnd) => unknown
	inError: (value: string[]) => unknown
	log: (value: string | symbol | PickType | Picker | Song) => unknown
	quote: (value: string) => unknown
}
