// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.

import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { Event } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	api: {
		ws: {
			route: {
				/**
				 * n​o​t​ ​a​ ​c​o​r​r​e​c​t​ ​d​i​a​l​o​g​ ​t​y​p​e​
			​{​p​a​r​s​e​E​r​r​o​r​}​
			​{​m​e​s​s​a​g​e​|​l​o​g​}
				 * @param {string} message
				 * @param {string} parseError
				 */
				dialogTypeError: RequiredParams<'message|log' | 'parseError'>
			}
		}
	}
	lib: {
		dialog: {
			/**
			 * n​o​t​ ​a​ ​c​o​r​r​e​c​t​ ​d​i​a​l​o​g​ ​t​y​p​e​
		​{​p​a​r​s​e​E​r​r​o​r​}​
		​{​m​e​s​s​a​g​e​|​l​o​g​}
			 * @param {string} message
			 * @param {string} parseError
			 */
			dialogTypeError: RequiredParams<'message|log' | 'parseError'>
			/**
			 * s​o​c​k​e​t​ ​e​r​r​o​r​:​ ​{​e​v​e​n​t​|​l​o​g​}
			 * @param {Event} event
			 */
			socketError: RequiredParams<'event|log'>
		}
	}
}

export type TranslationFunctions = {
	api: {
		ws: {
			route: {
				/**
				 * not a correct dialog type
			{parseError}
			{message|log}
				 */
				dialogTypeError: (arg: { message: string, parseError: string }) => LocalizedString
			}
		}
	}
	lib: {
		dialog: {
			/**
			 * not a correct dialog type
		{parseError}
		{message|log}
			 */
			dialogTypeError: (arg: { message: string, parseError: string }) => LocalizedString
			/**
			 * socket error: {event|log}
			 */
			socketError: (arg: { event: Event }) => LocalizedString
		}
	}
}

export type Formatters = {
	log: (value: string | Event) => unknown
}
