name: GitHub Pages

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build:
        env:
            PLANT_UML_VERSION: '1.2026.2'
        runs-on: ubuntu-latest
        steps:
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 24.x

            - uses: actions/checkout@master
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Build
              run: |
                  git submodule update --init --recursive
                  npm i pnpm -g
                  rm -rf package-lock.json
                  pnpm i
                  pnpm i
                  pnpm build

            - name: Gen PlantUML
              run: |
                  sudo apt-get update
                  sudo apt-get install -y graphviz fonts-wqy-microhei
                  sudo fc-cache -fv
                  wget https://github.com/plantuml/plantuml/releases/download/v${{ env.PLANT_UML_VERSION }}/plantuml-${{ env.PLANT_UML_VERSION }}.jar -O plantuml.jar
                  find . -name '*.puml' -type f -print0 | xargs -0 java -Dplantuml.font.default="WenQuanYi Micro Hei" -jar plantuml.jar -tsvg -charset UTF-8
                  rm -rf plantuml.jar

            - name: Save changes
              run: |
                  find . -name '.gitignore' -type f -print | xargs rm -rf
                  find . -type f -size +95M -delete
                  rm -rf .husky
                  git add .

            - name: Push Branch
              uses: actions-js/push@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: gh-pages
                  amend: true
                  force: true
